In [1]:
import torch

In [3]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(2,3))

In [4]:
print (a)
print (b)


tensor([[4, 1, 4],
        [2, 2, 3]])
tensor([[4, 3, 3],
        [1, 3, 1]])


In [5]:
a+b

tensor([[8, 4, 7],
        [3, 5, 4]])

In [6]:
torch.add(a,b)

tensor([[8, 4, 7],
        [3, 5, 4]])

In [7]:
result = torch.zeros(2,3)

In [8]:
torch.add(a,b,out=result)

tensor([[8., 4., 7.],
        [3., 5., 4.]])

In [9]:
result

tensor([[8., 4., 7.],
        [3., 5., 4.]])

In [10]:
#任何使张量发生变化的操作都需要加前缀“-”，例如a.add_(),b.sub_()
a.add_(b)  #a=a+b

tensor([[8, 4, 7],
        [3, 5, 4]])

In [11]:
a-b

tensor([[4, 1, 4],
        [2, 2, 3]])

In [12]:
a*b #对应位置相乘

tensor([[32, 12, 21],
        [ 3, 15,  4]])

In [13]:
a%b#取余数

tensor([[0, 1, 1],
        [0, 2, 0]])

In [14]:
a//b #取整数

tensor([[2, 1, 2],
        [3, 1, 4]])

In [26]:
tensor = torch.ones(3,5)

In [31]:
a = torch.randint(1,5,(2,3))
a = a.float()

In [32]:
torch.matmul(a,tensor)

tensor([[11., 11., 11., 11., 11.],
        [ 6.,  6.,  6.,  6.,  6.]])

In [33]:
a.T

tensor([[3., 2.],
        [4., 3.],
        [4., 1.]])