In [1]:
import torch

In [2]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.rand(3,4)

tensor([[0.9357, 0.4627, 0.2576, 0.5613],
        [0.4994, 0.6982, 0.4618, 0.1744],
        [0.6411, 0.9782, 0.0825, 0.0873]])

In [5]:
torch.randint(0,5,(2,3))

tensor([[2, 1, 1],
        [0, 4, 2]])

In [6]:
torch.randn(3,4)
#标准正态分布

tensor([[ 0.4651, -0.8431, -0.1167,  0.6985],
        [-0.4295, -0.2385,  0.2120,  0.5614],
        [-0.1074,  0.2199,  0.7754,  0.2350]])

In [9]:
a = torch.tensor([[1,2],
                 [2,3],
                 [4,5]])

In [10]:
a

tensor([[1, 2],
        [2, 3],
        [4, 5]])

In [12]:
b = torch.rand_like(a,dtype=float)

In [13]:
b

tensor([[0.1122, 0.5331],
        [0.6492, 0.7688],
        [0.5702, 0.4159]], dtype=torch.float64)

In [14]:
print(b.shape)
print(b.size)
#查看数据形状

torch.Size([3, 2])
<built-in method size of Tensor object at 0x7f83eafd41f8>


In [15]:
c = b.view(6)#相当于reshape

In [16]:
c

tensor([0.1122, 0.5331, 0.6492, 0.7688, 0.5702, 0.4159], dtype=torch.float64)

In [17]:
c[1].item()

0.5330512303365187

In [18]:
import numpy as np

In [19]:
np.array(c)

array([0.11217548, 0.53305123, 0.6492493 , 0.76881969, 0.57020025,
       0.4159397 ])

In [20]:
array = np.array([1,2,3])

In [21]:
array

array([1, 2, 3])