In [1]:
import torch

In [2]:
tensor = torch.arange(2,14)
print(tensor)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])


In [3]:
print(tensor[3])

tensor(5)


In [4]:
print(tensor[1:3])

tensor([3, 4])


In [5]:
print(tensor[-1])

tensor(13)


In [6]:
index = [1,3,5,-1]
tensor[index]

tensor([ 3,  5,  7, 13])